/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Yankees;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String arg[]) {
    	System.out.println("Hello");
        System.out.println("The end.....");
    	System.out.println("Change made here"); //New line added by yankees
        System.out.println("NOOOO DONT END");
        System.out.println("HAHAAHA, Redsox is gonna force push you out"); //New line added by RedSox
    }
}
