/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Yankees;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String arg[]) {
    	System.out.println("Hello");
        System.out.println("The end.....");
        System.out.println("NOOOO DONT END");
    }
}
